[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "neurodatagen"
version = "0.1.0"
description = "A module for neuroscience data generation"
authors = [
  {name = "Demetris Roumis", email = "8qdo8efl3@mozmail.com"},
]
readme = "README.md"
