name: neuro-waveform
channels:
  - conda-forge
dependencies:
  - python=3.9
  - holoviews
  - hvplot
  - panel
  - datashader
  - dask
  - numpy
  - pandas
  - xarray
  - ipykernel
  - jupyterlab
  - pyarrow