name: neuro-image-stack
channels:
  - conda-forge
dependencies:
  - python=3.9
  - holoviews
  - hvplot
  - panel
  - datashader
  - numpy
  - pandas
  - xarray
  - ipykernel
  - ffmpeg-python
  - jupyterlab
  - sparse
  - pip
  - pip:
    - -e ../../src/neurodatagen