name: tmp-neuro-stackedtimeseries
channels:
  - conda-forge
dependencies:
  - python
  - holoviews>=1.18.1
  - bokeh>=3.3.1
  - hvplot
  - panel
#  - datashader
  - numpy
  - pandas
#  - xarray
  - ipykernel
#  - mne
#  - neurodsp
  - jupyterlab
#  - intake
#  - zarr
#  - kerchunk
  - pip
  - pip:
    - holonote
 #   - -e ../../src/neurodatagen
 #   - -e ../../src/hvneuro
